export enum ForgotPasswordEnum {
  EMAIL_VERIFY = 'EMAIL_VERIFY',
  PHONE_VERIFY = 'PHONE_VERIFY',
  FORGOT_PASSWORD_WITH_EMAIL = 'FORGOT_PASSWORD_WITH_EMAIL',
  FORGOT_PASSWORD_WITH_PHONE = 'FORGOT_PASSWORD_WITH_PHONE',
  CHANGE_EMAIL = 'CHANGE_EMAIL',
  CHANGE_PHONE = 'CHANGE_PHONE',
}
